# Generated by Django 4.2 on 2023-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.IntegerField(verbose_name='Темпетатура'),
        ),
    ]
